---
layout: page
title: About
excerpt: Learn about Chops & Craft and it's author
permalink: /about/
---

Ahoy, my name is Paulo Phagula
footnote:[
Well actually, I'm *Pagula* but the folks at the registry messed things up.
You may also find other variants of the name written as *Pacula* or *Pacule*.
Also the *h* in *Pha* is silent, so you don't spell it like an "eff" as in "Pharmacy",
you spell it in the same way you start saying *Party*
]
and I'm a software engineer mainly interested
in web development, programming tools and technologies.
I'm https://www.youtube.com/watch?v=4E3xfR6IBII[not just a code monkey^]
though, my passion lies in developing software that adds value to businesses and
people's lives, from idea inception to shipping the final product.

This is my personal blog and brain dump, where I share my ideas and thoughts.
My usual nickname is **dareenzo** 🤦, hence the name of this blog.

I live in sunny https://en.wikipedia.org/wiki/Mozambique[Mozambique^]
☀️ 🇲🇿, but have been working in remote teams since forever.
Presently, I work at http://www.ux.co.mz[UX - Information Technologies^] as a
software engineer, crafting and managing innovative services to tackle employment,
education and financial inclusion challenges in emerging economies.

Along my career, I've worked in many domains, like Banking & Finances, Human Resources
& Recruiting, e-Governance, e-Commerce, and more.

// I hold a BS degree in Computer Science from http://www.ustm.ac.mz[Universidade São Tomás de Moçambique]
// with a specialization in Software Engineering.

Basically, I'm a tech enthusiast who loves to change people's lives by enhancing
their capabilities through software.
I'm an active contributor to open source projects and maintain a few of my own.

== Connect with me

If you want to know more about what I'm up to, please contact me directly or
follow me on these channels.

- dareenzo@gmail.com
- https://github.com/dareenzo[github.com/dareenzo^]
- https://twitter.com/dareenzo[twitter.com/dareenzo^]

If you're into spy stuff 🕵️ and would like to securely deliver a message to me,
my link:/key.asc[PGP key] 🔑 is `0x80726DF59BFDC5F0`.
The fingerprint is `31DD 9E65 D6F7 C19F 78DA 51FA 8072 6DF5 9BFD C5F0`
