---
layout: page
title: The Setup / Uses / Use this
excerpt: >
  This is a complete list of the tools, apps, services and hardware I use on a
  regular basis. The list contains tools I use in my work as a web developer but
  also tools I use at home.

  If you're interested in similar lists, I highly recommend that you visit the
  [[https://github.com/wesbos/awesome-uses][wesbos/awesome-uses repository on GitHub]].
permalink: /uses
last__update: Mar, 2021
---

Since i will never be interviewed for [[https://usesthis.com][Uses This]], I have interviewed myself.

* Who are you, and what do you do?
* What hardware do you use?

When I started to code professionally in 2015, it was the first time I came in
touch with a MacBook. I really like the finish of the hardware and stuck to it
since. But, my current MacBook slowly but surely gets old, though. I'm currently
waiting for the next release cycle of MacBooks and hope that Apple deprecates
the TouchBar and improves the keyboard. There isn't a week on Twitter where I
don't read about the issues people have with the butterfly-keyboard.

Devices I currently own:

- Apple MacBook Pro (Retina 13-inch, Late 2013)

** Audio
- JBL Flip  4

* And what software

Software is important to me. It helps me solve my problems on a daily basis. If
a service is great I don't hesitate to pay a monthly subscription or a one-time
fee.

** Global services

*** https://1password

Considered the best password manager for 2020 by Wirecutter - https://www.nytimes.com/wirecutter/reviews/best-password-managers/

https://1password.com

*** Google One

Google One is what you get when you pay for storage at Google. I mainly use the storage for Google Photos and to back up my NAS.

https://one.google.com
*** Google Drive & Google Photos
SInce I'm a paying user of Google One this just follows
*** Deezer

I listen to a lot of music (99'000 minutes in 2020 😱). It helps me concentrate
and focus on my work. While coding, I usually listen to soundtracks from movies
or games. For leisure time I like to listen to Hip Hop or Amapiano.

Here are some of my all time favourite albums and playlists.

- Whiplash
** macOS
*** Other apps
- Safari for everyday browsing
- Sequel Pro/TablePlus for working with databases
- Chrome for web development
- Karabiner Elements to remap certain key
- iTerm2
** Android

I don't have hundres of third-party apps on my iPhone. I've grown to love the
simplicity of most iOS stock apps over the years.

- Google Podcasts for the rare time I listen to podcasts
- Office Holelens for scanning receipts and documents with my phone
- Google Notes
-
** Ubuntu
 Kitty

#+begin_quote
It's the only software (besides Sublime) I run on my laptop that actually feels like it's using the 40 years of transistor improvements I'm paying for.
#+end_quote

- [[https://github.com/morhetz/gruvbox][Gruvbox]] Color scheme
- [[https://github.com/microsoft/cascadia-code][Cascadia Code]]  Font

  Monospaced font that includes programming ligatures and is designed to enhance
  the modern look and feel of the Windows Terminal

- [[https://fishshell.com/][fish shell]] - The user-friendly command line shell

  Surely, "Bash is the decease you'll die with, but won't die of", but:

  - This shell has a blazing fast startup
  - On top of that it has sane scripting ... which means no more ~fi~, ~esac~, and other oddities
  - Intuitive wildcard support
  - Function Autoloading
  - builtins:
    - math
    - string can be used in place of sed, grep, tr, cut, and awk in many situations
  - It has all of the goodies that zsh tries to emulate out of the box, namely:
    - Inline auto-suggestions based on history enabled by default
    - Smart Tab Suggestion - fish parses man pages and generated completion
    - Syntax highlighting of commands while they are typed
- [[https://startship.rs][🚀⭐️ Starship]] - The minimal, blazing-fast, and infinitely customizable prompt for any shell.
- [[https://github.com/tmux/tmux/wiki][tmux]] terminal multiplexer + [[https://github.com/tmuxinator/tmuxinator][tmuxinator]] (tmux session manager)
- [[https://neovim.io/][Neovim]] - Text universal text editor
- [[https://www.gnu.org/software/emacs/][Emacs]] - The one true editor

  #+begin_quote
  While any text editor can save your files, only Emacs can save your soul
  #+end_quote

  - I love /modal editing/ but not Vimscript. Also Bram Moolenar is nuts.
  - Emacs taught me lisp, the UNIX philosophy, literate programming, the true meaning of "trade of"
  - Emacs daemon - One emacs process handles all your frames whether you use a frame opened in a terminal via a ssh connection or X frames opened on the same host
- [[https://sw.kovidgoyal.net/kitty/][kitty]] - the fast, featureful, GPU based terminal emulator

  #+begin_quote
  It's the only software (besides Sublime) I run on my laptop that actually feels like it's using the 40 years of transistor improvements I'm paying for.
  #+end_quote
- Windows Terminal / WSL on Windows 10
- [[https://asdf-vm.com/][asdf-vm]] - Manage multiple runtime versions with a single CLI tool.

   asdf-vm is a CLI tool that can manage multiple language runtime versions on a per-project basis.
   It is like ~gvm~, ~nvm~, ~rbenv~ & ~pyenv~ (and more) all in one! Simply install your language's plugin!

    Why use asdf-vm?

  - single CLI for multiple languages
  - consistent commands to manage all your languages
  - single global config keeping defaults in one place
  - single ~.tool-versions~ config file per project
  - support for existing config files ~.node-version~, ~.nvmrc~, ~.ruby-version~ for easy migration
  - automatically switches runtime versions as you traverse your directories
  - simple plugin system to add support for your language of choice
  - shell completion available for common shells (Bash, Zsh, Fish)

- Rambox - Workspace browser

  Aggregates all the noise in chats in a single place so I can mute them at once

- MellowPlayer

  In the same spirit as Rambox aggregates all audio stream players in a single place.

- [[https://git-scm.com/][Git]] - source version control with config, global =.gitignore= file and aliases.
- [[https://www.perforce.com/products/helix-core-apps/merge-diff-tool-p4merge][p4merge]] - Merge and diff tool
- Firefox + [[https://vimium.github.io/][Vimium]] + [[https://youtu.be/Gy7lyvAfOSw][containers]] - Privacy aware web-browser with Vim keybindings
- VLC - The best OSS Media player for both audio and video
- [[https://www.dbcli.com/][dbcli]] - Commandline Database Clients with Autocompletion and Syntax Highlighting

* Roadtrip

A road trip is an adventure. It doesn’t matter how far you go. But all adventures require a little planning (and one or two backup plans, in case things go sideways).

* Adult

Being an adult can be messy, stressful business, but that doesn’t mean you
can’t have simple pleasures. Gear for people 21 and older cover sex toys,
marijuana tools, and more. Have fun and be safe,

** Condoms
- LifeStyles Skyn condoms
** Weed

* What woudl be your dream setup?

-----

For someone who claims not to be Google fanboy I surely do use many of their services
