---
version: 2
updates:
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    cooldown:
      default-days: 7
    groups:
      actions-minor-patch:
        patterns:
          - '*'
        update-types:
          - minor
          - patch
    commit-message:
      prefix: 'chore'
      include: 'scope'
  - package-ecosystem: 'bundler'
    directory: '/'
    schedule:
      interval: 'weekly'
    allow:
      - dependency-type: 'all'
    open-pull-requests-limit: 5
    cooldown:
      default-days: 7
    groups:
      bundler-minor-patch:
        patterns:
          - '*'
        update-types:
          - minor
          - patch
    commit-message:
      prefix: 'chore'
      include: 'scope'
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    cooldown:
      default-days: 7
    groups:
      npm-minor-patch:
        patterns:
          - '*'
        update-types:
          - minor
          - patch
    commit-message:
      prefix: 'chore'
      include: 'scope'
