# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Chops & Craft
email: pphagula@gmail.com
author: Paulo Phagula
description: > # this means to ignore newlines until "baseurl:"
  Paulo Phagula is a passionate software developer from Mozambique crafting websites and apps.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://dareenzo.github.io" # the base hostname & protocol for your site
twitter_username: dareenzo
github_username:  dareenzo
ga_tracking_id: UA-76527140-1

collections:
  notes:
    output: true
    permalink: /:collection/:name

# Build settings
markdown: kramdown
permalink: /blog/:year/:month/:day/:title/


exclude:
  - autoprefixer.yml
  - Gemfile*
  - README.md
  - LICENSE.md
  - tags/*.md
  - Rakefile

# sass compression
sass:
  sass_dir: _sass
  style: compressed

# html compression
compress_html:
  clippings: all
  comments: []
  endings: all
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: [html, head, body]
