# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Paulo Phagula
tagline: Full-stack Developer & aspiring entrepreneur
description: > # this means to ignore newlines until next "key:"
  Paulo Phagula's site and blog
url: "https://paulophagula.com" # the base hostname & protocol for your site
timezone: Africa/Maputo

author:
  name: Paulo Phagula
  email: paulo.phagula@gmail.com

header_links:
  - url: about
    title: Learn more bout me and this site

footer_links:
  twitter: PauloPhagula
  github: PauloPhagula
  linkedin: paulophagula
  stack_overflow: 6270740/paulo-phagula

google_analytics: UA-76527140-1
google_tag_manager: G-EQQW14PXHP
google_plus: PauloPhagula

# Permalinks
permalink: /blog/:year/:month/:day/:title/

# Build settings
markdown: kramdown
highlighter: none
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  syntax_highlighter_opts:
    disable : true

plugins:
  - jekyll-asciidoc
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-seo-tag
  # - jemoji

asciidoctor:
  attributes:
  - icons=font

# sass compression
sass:
  sass_dir: _sass
  style: compressed

# HTML compression
compress_html:
  clippings: all
  comments: []
  endings: all
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: [html, head, body]

# RSS feed
feed:
  path: feed.atom.xml

tags:

collections:
  notes:
    output: true
    permalink: /:collection/:name

  talks:
    output: true
    permalink: /:collection/:name

include:
  - _pages
# Exclude these files from your production _site
exclude:
  - autoprefixer.yml
  - Gemfile*
  - README.md
  - LICENSE.md
  - tags/*.md
  - Rakefile
  - Makefile
  - screenshot.png
  - vendor
  - post.sh
