# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Paulo Phagula
tagline: Musings on Software Engineering
description: > # this means to ignore newlines until next "key:"
  Paulo Phagula's Blog on Software Engineering and related topics
url: "https://dareenzo.github.io" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog
timezone: Africa/Maputo

author:
  name: Paulo Phagula
  email: pphagula@gmail.com

footer_links:
  twitter: dareenzo
  github: dareenzo
  linkedin: paulo-phagula
  stack_overflow: 6270740/paulo-phagula

google_analytics: UA-76527140-1
google_tag_manager: GTM-NCKZVZ
google_plus: PauloPhagula

# Permalinks
permalink: /blog/:year/:month/:day/:title/

# Build settings
markdown: kramdown
highlighter: none
kramdown:
  syntax_highlighter_opts:
    disable : true

plugins:
  - jekyll-asciidoc
  - jekyll-sitemap
  - jemoji
  - jekyll-redirect-from

asciidoctor:
  attributes:
  - icons=font

# sass compression
sass:
  sass_dir: _sass
  style: compressed

# HTML compression
compress_html:
  clippings: all
  comments: []
  endings: all
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: [html, head, body]

tags:

collections:
  notes:
    output: true
    permalink: /:collection/:name

  talks:
    output: true
    permalink: /:collection/:name

include:
  - _pages
# Exclude these files from your production _site
exclude:
  - autoprefixer.yml
  - Gemfile*
  - README.md
  - LICENSE.md
  - tags/*.md
  - Rakefile
  - build.sh
  - .travis.yml
  - screenshot.png
  - vendor
