name: Auto-merge Dependabot
on: pull_request

permissions:
  pull-requests: write
  contents: write

jobs:
  automerge:
    runs-on: ubuntu-latest
    if: github.event.pull_request.user.login == 'dependabot[bot]' && github.repository == github.event.pull_request.head.repo.full_name
    steps:
      - name: Enable Pull Request Automerge
        run: gh pr merge "$PR_NUMBER" --merge --auto
        env:
          GH_TOKEN: ${{ secrets.PAT }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
