name: notfoundbot
on:
  schedule:
    - cron: '0 13 * * MON'
  workflow_dispatch:
jobs:
  check:
    runs-on: ubuntu-slim
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10  # v6
        with:
          persist-credentials: false
      - name: Fix links
        uses: tmcw/notfoundbot@feeb668347f9c0ef8abdc4a8c43778fce2ee85d9  # v3.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
