---
# Based on https://github.com/actions/starter-workflows/blob/main/pages/jekyll.yml
name: Build

on:
  # Runs on pushes targeting the main branch
  push:
  # Allows you to run workflow manually from the actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment of GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false
      - name: Setup node
        uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'  # Not needed with a .ruby-version file
          bundler-cache: true  # runs 'bundle install' and caches installed gems automatically
          cache-version: 1  # Increment this number if you need to re-download cache gems
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5
        if: github.ref == 'refs/heads/main'
      - name: Build with Gulp
        # Outputs to the '/_site' directory
        run: pnpm exec gulp build
        env:
          JEKYLL_ENV: production
      - name: Upload Artifact
        # Automatically uploads an artifact from the '/_site' directory
        uses: actions/upload-pages-artifact@v4
        if: github.ref == 'refs/heads/main'
  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
