name: Security

on:
  pull_request:
    paths:
      - '.github/workflows/**'
  push:
    branches:
      - main
    paths:
      - '.github/workflows/**'
  schedule:
    - cron: '0 9 * * MON'
  workflow_dispatch:

jobs:
  zizmor:
    name: Workflow security scan
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10  # v6
        with:
          persist-credentials: false
      - name: Run zizmor
        uses: zizmorcore/zizmor-action@cc914d7f3750a2d13d75c7f184a1060aa0e9d482  # v0.6.4
        with:
          upload-sarif: true
          advanced-security: false
          annotations: true
